### ISSUE TITLE
Read/Store config settings EnOcean devices

### ISSUE THREAD

**Issue by Bascy** [I-Connect/EnOceanBleDevices#5]

**Comment by I-Connect** [comment]
There will multiple STM550 multisensors (bathroom and livingroom), shouldn't they also get 1 handler and a referenceid? (like the ptm)

1 stm550 can/will have multiple functions, like temperature, humidity and window/door open, whould it get multiple reference id's?

Can we create the handler within the marshaller? This would save hard coded declaration within csMain.h?

**Comment by Bascy** [comment]
Think you already solved this yourself

**Comment by Bascy** [comment]
STM550 and EMDCB handlers can be created runtime when registering a new device

**Comment by Bascy** [comment]
Storing registration is implemented by overwriting enocean config file when registering and unregistering devices
